# Generated by Django 6.0.3 on 2026-04-11 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_subject_marks_scheme'),
        ('exam_management', '0002_align_indexes_and_decimals'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='uniq_exam_name_per_class_section',
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Optional: make this exam subject-wise (e.g., class test for a single subject).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('exam_name', 'class_name', 'section', 'subject'), name='uniq_exam_name_per_class_section_subject'),
        ),
    ]
