# Generated by Django 6.0.3 on 2026-04-05 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(help_text='Parent user account', on_delete=django.db.models.deletion.PROTECT, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
