# Generated by Django 6.0.3 on 2026-04-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video')], default='PHOTO', max_length=20)),
                ('file', models.FileField(upload_to='reports/media/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food', models.TextField(blank=True, default='', help_text='Meals, appetite, snacks')),
                ('sleep', models.TextField(blank=True, default='', help_text='Nap time, duration')),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('OKAY', 'Okay'), ('SAD', 'Sad'), ('SICK', 'Sick')], default='OKAY', max_length=20)),
                ('learning', models.TextField(blank=True, default='', help_text='What the child learned')),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='classes.classroom')),
            ],
            options={
                'ordering': ['-date', 'student_id'],
            },
        ),
    ]
