# Generated by Django 6.0.3 on 2026-04-05 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('reports', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivityreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyactivityreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='students.student'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reports.dailyactivityreport'),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_progress_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='dailyactivityreport',
            constraint=models.UniqueConstraint(fields=('classroom', 'student', 'date'), name='uniq_daily_report_per_day'),
        ),
    ]
