# Generated by Django 6.0.3 on 2026-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_classteacher'),
        ('notifications', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('ALL_SCHOOL', 'All School'), ('TEACHERS', 'All Teachers'), ('PARENTS', 'All Parents')], default='ALL_SCHOOL', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='school_classes',
            field=models.ManyToManyField(blank=True, related_name='notices', to='academics.schoolclass'),
        ),
    ]
