# Generated by Django 6.0.3 on 2026-04-10 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notice_description_notice_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ADMIN_BROADCAST', 'Admin Broadcast'), ('SCHOOL_ANNOUNCEMENT', 'School Announcement'), ('HOLIDAY_NOTICE', 'Holiday Notice'), ('HOMEWORK_ASSIGNED', 'Homework Assigned'), ('EXAM_SCHEDULE_PUBLISHED', 'Exam Schedule Published'), ('EXAM_REMINDER', 'Exam Reminder'), ('RESULT_PUBLISHED', 'Result Published'), ('FEE_DUE_REMINDER', 'Fee Due Reminder'), ('ATTENDANCE_ABSENT_ALERT', 'Attendance Absent Alert'), ('LIVE_CLASS_REMINDER', 'Live Class Reminder'), ('MESSAGE', 'Message'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Optional schedule time; null = immediately visible', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry; after this time notifications hide', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_rows', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_inbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['publish_at'], name='notificatio_publish_c0f12f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_f8bca9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_141473_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='uniq_notification_user'),
        ),
    ]
