# Generated by Django 6.0.3 on 2026-04-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
