# Generated by Django 6.0.3 on 2026-04-06 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_subjectteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.subjectteacher'),
        ),
    ]
