# Generated by Django 6.0.3 on 2026-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subjectteacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacher',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
