# Generated by Django 6.0.3 on 2026-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'student_id'],
            },
        ),
    ]
