# Generated by Django 6.0.3 on 2026-04-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_subjectteacher_email'),
        ('attendance', '0003_initial'),
        ('students', '0003_student_class_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, default='', max_length=1)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_attendance_records', to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date', 'student_id'],
                'indexes': [models.Index(fields=['school_class', 'section', 'date'], name='attendance__school__3e15b8_idx'), models.Index(fields=['student', 'date'], name='attendance__student_9bea61_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_class', 'section', 'student', 'date'), name='uniq_academic_attendance_per_day')],
            },
        ),
    ]
