# Generated by Django 6.0.3 on 2026-04-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_subject_subject_teacher'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclassroutine',
            name='routine_type',
            field=models.CharField(choices=[('PERIOD', 'Period'), ('BREAK', 'Break')], default='PERIOD', max_length=10),
        ),
        migrations.AddField(
            model_name='academicclassroutine',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_routines', to='academics.subjectteacher'),
        ),
        migrations.AddField(
            model_name='academicclassroutine',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
