# Generated by Django 6.0.3 on 2026-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_academicclassroutine_routine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclassroutine',
            name='live_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicclassroutine',
            name='meet_event_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='academicclassroutine',
            name='meet_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
