# Generated by Django 6.0.3 on 2026-04-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_academicclassroutine_live_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClassRoutineOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meet_link', models.URLField(blank=True, default='')),
                ('meet_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='routines.academicclassroutine')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('routine', 'date'), name='uniq_routine_override_per_date')],
            },
        ),
    ]
