# Generated by Django 6.0.3 on 2026-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_specialliveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialliveclass',
            name='meet_event_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
