# Generated by Django 6.0.3 on 2026-04-10 04:01

import django.db.models.deletion
import homework_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0014_subject_marks_scheme'),
        ('students', '0003_student_class_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('homework_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('ASSIGNMENT', 'Assignment')], default='HOMEWORK', max_length=20)),
                ('section', models.CharField(blank=True, default='', max_length=1)),
                ('description', models.TextField(blank=True, default='', help_text='Rich HTML content from CKEditor 5')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=homework_management.models.homework_pdf_upload_to)),
                ('due_date', models.DateTimeField()),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='academics.schoolclass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='DRAFT', max_length=20)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('teacher_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('teacher_feedback', models.TextField(blank=True, default='')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework_management.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkGradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_grade_logs', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_logs', to='homework_management.homeworksubmission')),
            ],
            options={
                'ordering': ['-graded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=homework_management.models.submission_image_upload_to)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homework_management.homeworksubmission')),
            ],
            options={
                'ordering': ['page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotation_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_annotations_created', to=settings.AUTH_USER_MODEL)),
                ('submission_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='homework_management.submissionimage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['class_name', 'section', 'due_date'], name='homework_ma_class_n_6b2089_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['homework_type', 'status', 'due_date'], name='homework_ma_homewor_4746e0_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['homework', 'status'], name='homework_ma_homewor_5b98bd_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['student', 'status'], name='homework_ma_student_c52ede_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(fields=('homework', 'student'), name='uniq_homework_student_submission'),
        ),
        migrations.AddIndex(
            model_name='homeworkgradelog',
            index=models.Index(fields=['submission', 'graded_at'], name='homework_ma_submiss_36a2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionimage',
            index=models.Index(fields=['submission', 'page_number'], name='homework_ma_submiss_538f5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionimage',
            constraint=models.UniqueConstraint(fields=('submission', 'page_number'), name='uniq_submission_page_number'),
        ),
        migrations.AddIndex(
            model_name='submissionannotation',
            index=models.Index(fields=['submission_image', 'created_at'], name='homework_ma_submiss_196b1b_idx'),
        ),
    ]
