# Generated by Django 6.0.3 on 2026-04-13 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def populate_homework_class_date(apps, schema_editor):
    Homework = apps.get_model("homework_management", "Homework")
    SpecialLiveClass = apps.get_model("classes", "SpecialLiveClass")

    tz = timezone.get_default_timezone()

    slc_ids = list(
        Homework.objects.exclude(special_live_class_id=None)
        .values_list("special_live_class_id", flat=True)
        .distinct()
    )
    slc_dates = {}
    if slc_ids:
        slc_dates = dict(SpecialLiveClass.objects.filter(id__in=slc_ids).values_list("id", "date"))

    for hw in Homework.objects.filter(class_date__isnull=True).only("id", "due_date", "special_live_class_id").iterator():
        if hw.special_live_class_id and hw.special_live_class_id in slc_dates:
            class_date = slc_dates[hw.special_live_class_id]
        else:
            dt = hw.due_date
            if dt and timezone.is_naive(dt):
                dt = timezone.make_aware(dt, tz)
            class_date = timezone.localtime(dt, tz).date() if dt else None

        if class_date:
            Homework.objects.filter(id=hw.id).update(class_date=class_date)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_subject_marks_scheme'),
        ('classes', '0004_specialliveclass_meet_event_id'),
        ('homework_management', '0003_homework_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='class_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='special_live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='classes.specialliveclass'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['class_name', 'section', 'class_date'], name='homework_ma_class_n_1b3b42_idx'),
        ),
        migrations.RunPython(populate_homework_class_date, migrations.RunPython.noop),
    ]
