# Generated by Django 6.0.3 on 2026-04-08 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='portal_role',
            field=models.ForeignKey(blank=True, help_text='Optional RBAC role for portal sidebar + CRUD permissions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.portalrole'),
        ),
        migrations.CreateModel(
            name='PortalRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.portalrole')),
            ],
            options={
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('role', 'path'), name='uniq_portal_role_path')],
            },
        ),
    ]
